services:
  postgres-auth:
    image: postgres:17
    container_name: finflow-postgres-auth
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
