const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const ROLES = ["MERCHANT_ADMIN", "MERCHANT_USER"] as const;
const USER_STATUSES = ["ACTIVE", "INACTIVE"] as const;
export type ManagedMerchantRole = (typeof ROLES)[number];
export type ManagedMerchantUserStatus = (typeof USER_STATUSES)[number];
function stringField(value: unknown, field: string, max = 255) { if (typeof value !== "string" || !value.trim()) throw new Error(`${field} is required`); const result = value.trim(); if (result.length > max) throw new Error(`${field} must be at most ${max} characters`); return result; }
function positiveInt(value: string | undefined, field: string) { const id = Number(value); if (!Number.isInteger(id) || id <= 0) throw new Error(`${field} must be a positive integer`); return id; }
export function parseManagedMerchantId(value: string | undefined) { return positiveInt(value, "merchantId"); }
export function parseManagedResourceId(value: string | undefined, field: string) { return positiveInt(value, field); }
export function validateMerchantUser(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const userId = Number(input.userId); if (!Number.isInteger(userId) || userId <= 0) throw new Error("userId must be a positive integer"); const role = input.role ?? "MERCHANT_USER"; if (typeof role !== "string" || !ROLES.includes(role as ManagedMerchantRole)) throw new Error("invalid merchant role"); return { userId, role: role as ManagedMerchantRole }; }
export function validateMerchantUserUpdate(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const result: { role?: ManagedMerchantRole; status?: ManagedMerchantUserStatus } = {}; if (input.role !== undefined) { if (typeof input.role !== "string" || !ROLES.includes(input.role as ManagedMerchantRole)) throw new Error("invalid merchant role"); result.role = input.role as ManagedMerchantRole; } if (input.status !== undefined) { if (typeof input.status !== "string" || !USER_STATUSES.includes(input.status as ManagedMerchantUserStatus)) throw new Error("invalid merchant user status"); result.status = input.status as ManagedMerchantUserStatus; } if (!Object.keys(result).length) throw new Error("role or status is required"); return result; }
export function validateSettings(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const result: { timezone?: string; currency?: string; notificationsEnabled?: boolean; metadata?: Record<string, unknown> } = {}; if (input.timezone !== undefined) result.timezone = stringField(input.timezone, "timezone", 100); if (input.currency !== undefined) { const currency = stringField(input.currency, "currency", 3).toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) throw new Error("currency must be a 3-letter ISO code"); result.currency = currency; } if (input.notificationsEnabled !== undefined) { if (typeof input.notificationsEnabled !== "boolean") throw new Error("notificationsEnabled must be boolean"); result.notificationsEnabled = input.notificationsEnabled; } if (input.metadata !== undefined) { if (!input.metadata || typeof input.metadata !== "object" || Array.isArray(input.metadata)) throw new Error("metadata must be an object"); result.metadata = input.metadata as Record<string, unknown>; } if (!Object.keys(result).length) throw new Error("at least one field is required"); return result; }
export function validateInvitation(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const email = stringField(input.email, "email").toLowerCase(); if (!EMAIL_REGEX.test(email)) throw new Error("email must be valid"); const role = input.role ?? "MERCHANT_USER"; if (typeof role !== "string" || !ROLES.includes(role as ManagedMerchantRole)) throw new Error("invalid merchant role"); return { email, role: role as ManagedMerchantRole }; }
export function validateAcceptInvitation(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const token = stringField((body as Record<string, unknown>).token, "token", 256); return { token }; }
export function validateApiKey(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const name = stringField(input.name, "name", 100); let expiresAt: Date | undefined; if (input.expiresAt !== undefined && input.expiresAt !== null) { expiresAt = new Date(String(input.expiresAt)); if (Number.isNaN(expiresAt.getTime()) || expiresAt <= new Date()) throw new Error("expiresAt must be a future date"); } return { name, expiresAt }; }
const WEBHOOK_EVENTS = ["payment.created", "payment.updated", "payment.failed", "merchant.updated"] as const;
export function validateWebhook(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const url = stringField(input.url, "url", 2048); let parsed: URL; try { parsed = new URL(url); } catch { throw new Error("url must be valid"); } if (!["http:", "https:"].includes(parsed.protocol)) throw new Error("url must use http or https"); const events = input.events ?? []; if (!Array.isArray(events) || events.some((event) => typeof event !== "string" || !WEBHOOK_EVENTS.includes(event as (typeof WEBHOOK_EVENTS)[number]))) throw new Error(`events must contain only: ${WEBHOOK_EVENTS.join(", ")}`); const enabled = input.enabled === undefined ? true : input.enabled; if (typeof enabled !== "boolean") throw new Error("enabled must be boolean"); return { url, events: events as string[], enabled }; }
export function validateWebhookUpdate(body: unknown) { if (!body || typeof body !== "object") throw new Error("request body is required"); const input = body as Record<string, unknown>; const result: { url?: string; events?: string[]; enabled?: boolean } = {}; if (input.url !== undefined) result.url = validateWebhook({ url: input.url, events: [] }).url; if (input.events !== undefined) result.events = validateWebhook({ url: "https://example.com", events: input.events }).events; if (input.enabled !== undefined) { if (typeof input.enabled !== "boolean") throw new Error("enabled must be boolean"); result.enabled = input.enabled; } if (!Object.keys(result).length) throw new Error("at least one field is required"); return result; }
